package com.taxin60sec.backend.workflow;

import com.taxin60sec.backend.entity.*;
import com.taxin60sec.backend.entity.enums.*;
import com.taxin60sec.backend.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.util.*;

@Service @RequiredArgsConstructor @Transactional
public class CaseIntelligenceService {
 private final CaseRepository cases; private final RequiredDocumentRepository required; private final UploadedDocumentRepository uploaded; private final TimelineEventRepository timeline; private final UserRepository users;
 @Transactional(readOnly=true) public DocumentChecklist checklist(Long caseId){List<RequiredDocument> r=required.findByTaxCaseIdAndDeletedFalseOrderByDisplayOrderAsc(caseId);Set<Long> ok=uploaded.findByTaxCaseIdAndDeletedFalseOrderByCreatedAtDesc(caseId).stream().filter(d->d.getVerificationStatus()==DocumentVerificationStatus.VERIFIED&&d.getRequiredDocument()!=null).map(d->d.getRequiredDocument().getId()).collect(java.util.stream.Collectors.toSet());List<String> missing=r.stream().filter(d->d.isMandatory()&&!ok.contains(d.getId())).map(RequiredDocument::getName).toList();List<String> optional=r.stream().filter(d->!d.isMandatory()&&!ok.contains(d.getId())).map(RequiredDocument::getName).toList();int total=(int)r.stream().filter(RequiredDocument::isMandatory).count();return new DocumentChecklist(caseId,missing,optional,total-missing.size(),total,total==0?100:(int)Math.round((total-missing.size())*100D/total));}
 public List<Question> questions(Long caseId){Case c=caseOf(caseId);List<Question> out=new ArrayList<>();checklist(caseId).missing().forEach(n->out.add(new Question("DOCUMENT_"+n.replaceAll("\\W+","_"),"Please upload "+n+".","DOCUMENT")));uploaded.findByTaxCaseIdAndDeletedFalseOrderByCreatedAtDesc(caseId).forEach(d->{if(d.getOcrConfidence()!=null&&d.getOcrConfidence()<.6)out.add(new Question("OCR_"+d.getId(),"Please provide a clearer copy of "+d.getOriginalFilename()+".","OCR"));if(!d.isOwnershipValidated())out.add(new Question("OWNERSHIP_"+d.getId(),"Please confirm ownership of "+d.getOriginalFilename()+".","OWNERSHIP"));});if(c.getDescription()==null||c.getDescription().isBlank())out.add(new Question("SERVICE_DETAILS","Please describe the business requirement for "+c.getServiceOffering().getDisplayName()+".","SERVICE"));return out;}
 public PriceEstimate estimate(Long caseId){Case c=caseOf(caseId);ServiceOffering s=c.getServiceOffering();BigDecimal min=price(s.getMinimumPrice(),s.getBasePrice());BigDecimal max=price(s.getMaximumPrice(),min);BigDecimal m=switch(c.getPriority()){case URGENT->new BigDecimal("1.50");case HIGH->new BigDecimal("1.25");case LOW->new BigDecimal("0.90");default->BigDecimal.ONE;};int missing=checklist(caseId).missing().size();m=m.add(new BigDecimal("0.05").multiply(BigDecimal.valueOf(Math.min(missing,4))));min=min.multiply(m).setScale(2,RoundingMode.HALF_UP);max=max.multiply(m).setScale(2,RoundingMode.HALF_UP);int days=Math.max(1,Optional.ofNullable(s.getEstimatedCompletionDays()).orElse(7)+(c.getPriority()==CasePriority.URGENT?-2:missing));c.setEstimatedMinimumPrice(min);c.setEstimatedMaximumPrice(max);c.setEstimatedDurationDays(days);return new PriceEstimate(min,max,days,c.getPriority().name(),"Calculated from catalog pricing, urgency and document completeness.");}
 public CaseSummary summary(Long caseId){Case c=caseOf(caseId);DocumentChecklist docs=checklist(caseId);PriceEstimate p=estimate(caseId);List<String> risks=new ArrayList<>();List<Map<String,String>> extract=new ArrayList<>();uploaded.findByTaxCaseIdAndDeletedFalseOrderByCreatedAtDesc(caseId).forEach(d->{if(d.isCorrupted())risks.add(d.getOriginalFilename()+" is corrupt");if(d.isEncrypted())risks.add(d.getOriginalFilename()+" is encrypted");if(d.isDuplicateFile())risks.add(d.getOriginalFilename()+" is duplicate");if(d.getValidationIssues()!=null&&!d.getValidationIssues().isBlank())risks.add(d.getValidationIssues());extract.add(Map.of("id",String.valueOf(d.getId()),"type",String.valueOf(d.getClassifiedDocumentType()),"ocrConfidence",String.valueOf(d.getOcrConfidence())));});if(!docs.missing().isEmpty())risks.add("Mandatory documents are missing");String text="Client: "+c.getClient().getFullName()+". Service: "+c.getServiceOffering().getDisplayName()+". Completion: "+docs.completionPercentage()+"%. Missing: "+String.join(", ",docs.missing())+". Suggested price: ₹"+p.minimumPrice()+"–₹"+p.maximumPrice()+". Timeline: "+p.durationDays()+" days.";c.setIntakeSummary(text);c.setAiRiskFlags(String.join(" | ",risks));return new CaseSummary(text,docs,extract,risks,questions(caseId),p);}
 public ReviewResult review(Long caseId,ReviewCommand command,User actor){Case c=caseOf(caseId);if(command.assigneeId()!=null)c.setAssignedCa(users.findById(command.assigneeId()).orElseThrow(()->new NoSuchElementException("Assignee not found")));if(command.internalNotes()!=null)c.setInternalNotes(command.internalNotes());if(command.action()==ReviewAction.APPROVE){c.setStatus(CaseStatus.IN_PROGRESS);c.setWorkflowStage(WorkflowStage.PROCESSING);}else if(command.action()==ReviewAction.REJECT){c.setStatus(CaseStatus.CANCELLED);c.setWorkflowStage(WorkflowStage.CANCELLED);c.setRemarks(command.reason());}else{c.setWorkflowStage(WorkflowStage.CLIENT_ACTION_REQUIRED);c.setRemarks(command.reason());}TimelineEvent e=new TimelineEvent();e.setTaxCase(c);e.setActor(actor);e.setEventType("CA_"+command.action());e.setTitle("CA review action recorded");e.setDescription(command.reason());timeline.save(e);return new ReviewResult(c.getWorkflowStage().name(),c.getStatus().name(),c.getInternalNotes());}
 private Case caseOf(Long id){return cases.findById(id).filter(c->!c.isDeleted()).orElseThrow(()->new NoSuchElementException("Case not found"));}private BigDecimal price(BigDecimal value,BigDecimal fallback){return value!=null?value:(fallback!=null?fallback:BigDecimal.ZERO);} public record DocumentChecklist(Long caseId,List<String> missing,List<String> optional,int completedMandatory,int totalMandatory,int completionPercentage){}public record Question(String code,String text,String category){}public record PriceEstimate(BigDecimal minimumPrice,BigDecimal maximumPrice,int durationDays,String priority,String reason){}public record CaseSummary(String summary,DocumentChecklist documents,List<Map<String,String>> extractedInformation,List<String> risks,List<Question> followUpQuestions,PriceEstimate pricing){}public enum ReviewAction{APPROVE,REJECT,REQUEST_INFORMATION}public record ReviewCommand(ReviewAction action,String reason,String internalNotes,Long assigneeId){}public record ReviewResult(String workflowStage,String status,String internalNotes){}
}
