spring.datasource.url=${SPRING_DATASOURCE_URL} 
spring.datasource.username=${SPRING_DATASOURCE_USERNAME} 
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB



server.port=${PORT:8080}

whatsapp.access-token=EAAOzzoZCbOwsBSJMMd3FvxOHUoK3PKNK1owXJ8whAVYVrByS4jUqn5IlieAQgn3DKgtx0fTkYfe4XZBt0dqxospq58n38ri13TvoiqVOOim8NlwYn6WZCeGnY6mpffCXquHZBbZAZCx8XfloxTuKJMwAZBHTFI1Edq5z2C77ZCVA4PC7ApWhovnuZAFpyQYj5ZBexHAybSbiZAxWleq5oRv6W73ZAXevTOEomB2o2nl0VZA7orzQuIs5ta2ygaZAUY3D1xKZA6nU8SgyAsjaiObONZB4zzcz
whatsapp.phone-number-id=1200927639772790
whatsapp.verify-token=taxin60sec123
whatsapp.graph-api-version=v23.0