package com.taxin60sec.backend.controller;

import com.taxin60sec.backend.common.*;
import com.taxin60sec.backend.dto.business.*;
import com.taxin60sec.backend.dto.domain.*;
import com.taxin60sec.backend.entity.enums.*;
import com.taxin60sec.backend.security.UserPrincipal;
import com.taxin60sec.backend.service.BusinessService;
import jakarta.validation.Valid;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;
import java.util.*;

final class BusinessApi { static <T> ApiResponse<T> ok(T data){return ApiResponse.success("Success",data,null);} static void client(BusinessService s,Long id,UserPrincipal p){if(!Objects.equals(s.getCase(id).clientId(),p.getId()))throw new AccessDeniedException("Case does not belong to current client");} static void ca(BusinessService s,Long id,UserPrincipal p){if(!s.assignedTo(id,p.getUser()))throw new AccessDeniedException("Case is not assigned to current CA");} static void caseAccess(BusinessService s,Long id,UserPrincipal p){if(p.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_ADMIN")))return;if(p.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_CA"))){ca(s,id,p);return;}client(s,id,p);} }

@RestController @RequestMapping("/api/v1/cases") @PreAuthorize("hasRole('CLIENT')")
class ClientCaseController { private final BusinessService s; ClientCaseController(BusinessService s){this.s=s;}
 @PostMapping public ApiResponse<CaseDto> create(@Valid @RequestBody CaseRequests.Create r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.createCase(r,p.getUser()));}
 @PutMapping("/{id}") public ApiResponse<CaseDto> update(@PathVariable Long id,@Valid @RequestBody CaseRequests.Update r,@AuthenticationPrincipal UserPrincipal p){BusinessApi.client(s,id,p);return BusinessApi.ok(s.updateCase(id,r,p.getUser()));}
 @GetMapping public ApiResponse<PageResponse<CaseDto>> list(@AuthenticationPrincipal UserPrincipal p,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort,@RequestParam(required=false)String query,@RequestParam(required=false)WorkflowStage stage,@RequestParam(required=false)CasePriority priority,@RequestParam(required=false)CaseStatus status){return BusinessApi.ok(s.listCases(p.getId(),null,query,stage,priority,status,null,null,page,size,sort));}
 @GetMapping("/{id}") public ApiResponse<CaseDto> get(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){BusinessApi.client(s,id,p);return BusinessApi.ok(s.getCase(id));}
 @PostMapping("/{id}/cancel") public ApiResponse<CaseDto> cancel(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){BusinessApi.client(s,id,p);return BusinessApi.ok(s.status(id,CaseStatus.CANCELLED,p.getUser()));}
 @PostMapping("/{id}/archive") public ApiResponse<CaseDto> archive(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){BusinessApi.client(s,id,p);return BusinessApi.ok(s.archive(id,false,p.getUser()));}}

@RestController @RequestMapping("/api/v1/admin/cases")
class AdminCaseController {private final BusinessService s;AdminCaseController(BusinessService s){this.s=s;}
 @GetMapping public ApiResponse<PageResponse<CaseDto>> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort,@RequestParam(required=false)String query,@RequestParam(required=false)WorkflowStage stage,@RequestParam(required=false)CasePriority priority,@RequestParam(required=false)CaseStatus status,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return BusinessApi.ok(s.listCases(null,null,query,stage,priority,status,from,to,page,size,sort));}
 @PutMapping("/{id}/assign") public ApiResponse<CaseDto> assign(@PathVariable Long id,@Valid @RequestBody CaseRequests.Assignment r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.assign(id,r.caUserId(),p.getUser()));}
 @PutMapping("/{id}/priority") public ApiResponse<CaseDto> priority(@PathVariable Long id,@Valid @RequestBody CaseRequests.Priority r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.priority(id,r.priority(),p.getUser()));}
 @PutMapping("/{id}/stage") public ApiResponse<CaseDto> stage(@PathVariable Long id,@Valid @RequestBody CaseRequests.Stage r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.stage(id,r.stage(),p.getUser()));}
 @PutMapping("/{id}/status") public ApiResponse<CaseDto> status(@PathVariable Long id,@Valid @RequestBody CaseRequests.Status r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.status(id,r.status(),p.getUser()));}
 @PostMapping("/{id}/archive") public ApiResponse<CaseDto> archive(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.archive(id,false,p.getUser()));}@PostMapping("/{id}/restore") public ApiResponse<CaseDto> restore(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.archive(id,true,p.getUser()));}
 @GetMapping("/dashboard") public ApiResponse<Map<String,Long>> dashboard(){return BusinessApi.ok(s.statistics(null));}}

@RestController @RequestMapping("/api/v1/ca/cases") @PreAuthorize("hasRole('CA')")
class CaCaseController {private final BusinessService s;CaCaseController(BusinessService s){this.s=s;}@GetMapping public ApiResponse<PageResponse<CaseDto>> list(@AuthenticationPrincipal UserPrincipal p,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return BusinessApi.ok(s.listCases(null,p.getId(),null,null,null,null,null,null,page,size,sort));}@PostMapping("/{id}/accept")public ApiResponse<CaseDto> accept(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){BusinessApi.ca(s,id,p);return BusinessApi.ok(s.accept(id,p.getUser()));}@PostMapping("/{id}/reject")public ApiResponse<CaseDto> reject(@PathVariable Long id,@Valid @RequestBody DocumentRequests.Reject r,@AuthenticationPrincipal UserPrincipal p){BusinessApi.ca(s,id,p);return BusinessApi.ok(s.reject(id,r.reason(),p.getUser()));}@PutMapping("/{id}/notes")public ApiResponse<CaseDto> notes(@PathVariable Long id,@Valid @RequestBody CaseRequests.Notes r,@AuthenticationPrincipal UserPrincipal p){BusinessApi.ca(s,id,p);return BusinessApi.ok(s.notes(id,r.internalNotes(),p.getUser()));}@PutMapping("/{id}/stage")public ApiResponse<CaseDto> stage(@PathVariable Long id,@Valid @RequestBody CaseRequests.Stage r,@AuthenticationPrincipal UserPrincipal p){BusinessApi.ca(s,id,p);return BusinessApi.ok(s.stage(id,r.stage(),p.getUser()));}@PostMapping("/{id}/complete")public ApiResponse<CaseDto> complete(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.complete(id,p.getUser()));}@GetMapping("/statistics")public ApiResponse<Map<String,Long>> stats(@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.statistics(p.getId()));}}

@RestController @RequestMapping("/api/v1/services")
class CatalogController {private final BusinessService s;CatalogController(BusinessService s){this.s=s;}@GetMapping public ApiResponse<PageResponse<ServiceOfferingDto>> list(@RequestParam(required=false)String query,@RequestParam(required=false)ServiceCategory category,@RequestParam(required=false)Boolean active,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return BusinessApi.ok(s.listServices(query,category,active,page,size,sort));}@PostMapping @PreAuthorize("hasRole('ADMIN')")public ApiResponse<ServiceOfferingDto> create(@Valid @RequestBody CatalogRequests.Service r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.saveService(null,r,p.getUser()));}@PutMapping("/{id}")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<ServiceOfferingDto> update(@PathVariable Long id,@Valid @RequestBody CatalogRequests.Service r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.saveService(id,r,p.getUser()));}@DeleteMapping("/{id}")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<Void> delete(@PathVariable Long id){s.deleteService(id);return BusinessApi.ok(null);}@PutMapping("/{id}/active")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<ServiceOfferingDto> active(@PathVariable Long id,@RequestParam boolean value){return BusinessApi.ok(s.setServiceFlag(id,"active",value));}@PutMapping("/{id}/featured")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<ServiceOfferingDto> featured(@PathVariable Long id,@RequestParam boolean value){return BusinessApi.ok(s.setServiceFlag(id,"featured",value));}@GetMapping("/{id}/required-documents")public ApiResponse<List<RequiredDocumentDto>> required(@PathVariable Long id){return BusinessApi.ok(s.requiredForService(id));}@PostMapping("/{id}/required-documents")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<RequiredDocumentDto> createRequired(@PathVariable Long id,@Valid @RequestBody CatalogRequests.RequiredDocument r){return BusinessApi.ok(s.saveRequired(id,null,r));}@PutMapping("/required-documents/{docId}")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<RequiredDocumentDto> updateRequired(@PathVariable Long docId,@Valid @RequestBody CatalogRequests.RequiredDocument r){return BusinessApi.ok(s.saveRequired(null,docId,r));}@DeleteMapping("/required-documents/{docId}")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<Void> deleteRequired(@PathVariable Long docId){s.deleteRequired(docId);return BusinessApi.ok(null);}@PutMapping("/{id}/required-documents/reorder")@PreAuthorize("hasRole('ADMIN')")public ApiResponse<Void> reorder(@PathVariable Long id,@Valid @RequestBody CatalogRequests.Reorder r){s.reorder(id,r.documentIds());return BusinessApi.ok(null);}}

@RestController @RequestMapping("/api/v1/cases/{caseId}/documents")
class CaseDocumentController {private final BusinessService s;CaseDocumentController(BusinessService s){this.s=s;}@GetMapping public ApiResponse<List<UploadedDocumentDto>> list(@PathVariable Long caseId,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.documents(caseId));}@PostMapping public ApiResponse<UploadedDocumentDto> create(@PathVariable Long caseId,@Valid @RequestBody DocumentRequests.Create r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.createDocument(caseId,r,p.getUser()));}@GetMapping("/missing")public ApiResponse<List<RequiredDocumentDto>> missing(@PathVariable Long caseId){return BusinessApi.ok(s.missing(caseId));}@GetMapping("/timeline")public ApiResponse<List<TimelineEventDto>> timeline(@PathVariable Long caseId){return BusinessApi.ok(s.timeline(caseId));}@PutMapping("/{id}")public ApiResponse<UploadedDocumentDto> update(@PathVariable Long caseId,@PathVariable Long id,@Valid @RequestBody DocumentRequests.Update r){return BusinessApi.ok(s.updateDocument(id,r));}@DeleteMapping("/{id}")public ApiResponse<Void> delete(@PathVariable Long caseId,@PathVariable Long id){s.deleteDocument(id);return BusinessApi.ok(null);}@PostMapping("/{id}/approve")@PreAuthorize("hasAnyRole('CA','ADMIN')")public ApiResponse<UploadedDocumentDto> approve(@PathVariable Long caseId,@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.verifyDocument(id,true,null,p.getUser()));}@PostMapping("/{id}/reject")@PreAuthorize("hasAnyRole('CA','ADMIN')")public ApiResponse<UploadedDocumentDto> reject(@PathVariable Long caseId,@PathVariable Long id,@Valid @RequestBody DocumentRequests.Reject r,@AuthenticationPrincipal UserPrincipal p){return BusinessApi.ok(s.verifyDocument(id,false,r.reason(),p.getUser()));}}
