ALTER TABLE cases ADD COLUMN IF NOT EXISTS intake_answers VARCHAR(12000);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS intake_summary VARCHAR(4000);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS intake_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS intake_questions VARCHAR(6000);
